import {
  AUDTDATA,
  BREGDICT,
  COMMDICT,
  DESLDIC5,
  DOCCDAT5,
  HISDAT5,
  LABNDAT4,
  LOCKDAT5,
  LOCNDIC4,
  ORDRDAT5,
  ORDRDIC5,
  PARMDICT,
  PRINTQ4,
  RDNMIDX4,
  RDOBIDX4,
  RDOCIDX4,
  REGDAT4,
  RIDNIDX4,
  RLIDIDX4,
  RLNKIDX4,
  RLNMIDX4,
  RLOCIDX4,
  RLSXIDX4,
  RNAMIDX4,
  RREFIDX4,
  RSNXIDX4,
  RTKNIDX5,
  RULEDIC5,
  STOADAT5,
  SYSTDIC5,
  TESTDATA,
  TESTDICT,
  TXT1DATA,
  WARDDICT,
  WLSTDAT6,
  WRKADICT,
} from "disalab";
import type { DisaServer } from "disalab";

export interface EntityQueryClass {
  All(where: string, server: DisaServer): Promise<unknown[]>;
}

export interface EntityDef {
  alias: string;
  class: EntityQueryClass;
  tableName: string;
  /** Columns that actually exist in the SQL table — safe to use in --where / --order-by. */
  sqlColumns: string[];
  /** All properties exposed on the hydrated JS object (SQL columns + byte-decoded fields). */
  fields: string[];
  cursorColumn?: string;
  notes?: string;
}

const REGDAT4_FIELDS = [
  "LabNumber",
  "Index",
  "UniqueID",
  "RegisteredDatetime",
  "ReferenceNumber",
  "ReceivedInLabDateTime",
  "CollectedDatetime",
  "TakenDateTime",
  "ReceivedBy",
  "ModifiedBy",
  "InnerLabNumber",
  "RefNos",
  "NID",
  "Location",
  "WardClinic",
  "FolderNumber",
  "Name",
  "DobAge",
  "Sex",
  "Surname",
  "Middlename",
  "Firstname",
  "Specimen",
  "Condition",
  "Priority",
  "Therapy",
  "Notes",
  "DiagCln",
  "Ref_Dr_ID",
  "Ref_Dr",
  "Receipt",
  "Amount",
  "PaidBy",
  "Tests",
  "TestOrders",
  "CollectedBy",
  "TakenBy",
  "ReceivedInLabBy",
  "Phone",
  "Work",
  "Mobile",
  "Email",
  "Ref_Dr_Mobile",
  "Ref_Dr_Email",
  "Ref_Dr_Phone",
  "Ref_Dr_Fax",
  "PostalAddress1",
  "PostalAddress2",
  "PostalAddress3",
  "NotesText",
  "TherapyText",
  "DiagClnText",
  "ICD10",
  "SpecimenText",
];

const ENTITY_DEFS: EntityDef[] = [
  {
    alias: "registration",
    class: REGDAT4,
    tableName: "[DisalabData].[dbo].[REGDAT4]",
    sqlColumns: ["LabNo"],
    fields: REGDAT4_FIELDS,
    cursorColumn: "LabNo",
    notes:
      "Specimen registration. Most fields (Region, NID, Name, Specimen, etc.) are decoded from the REGDAT4_STATUS binary blob — only `LabNo` is a real SQL column. Use LabNo in --where.",
  },
  {
    alias: "test-result",
    class: TESTDATA,
    tableName: "[DisalabData].[dbo].[TESTDATA]",
    sqlColumns: ["DATESTAMP", "LABNO", "TESTCODE", "TESTINDEX"],
    fields: ["DATESTAMP", "LABNO", "TESTCODE", "TESTINDEX", "ORDER"],
    cursorColumn: "LABNO",
    notes: "ORDER field is built per-row by hydrating TXT1DATA + dictionaries (slow).",
  },
  {
    alias: "order",
    class: ORDRDAT5,
    tableName: "[DisalabData].[dbo].[ORDRDAT5]",
    sqlColumns: [
      "DATESTAMP",
      "PlacerOrderNo",
      "RefNo",
      "OrderStatus",
      "CollectedDateTime",
      "Labno",
      "Region",
      "HospitalNo",
    ],
    fields: [
      "DATESTAMP",
      "PlacerOrderNo",
      "RefNo",
      "OrderStatus",
      "CollectedDateTime",
      "Labno",
      "Region",
      "HospitalNo",
      "_PlacerOrderNo",
    ],
    cursorColumn: "Labno",
  },
  {
    alias: "text",
    class: TXT1DATA,
    tableName: "[DisalabData].[dbo].[TXT1DATA]",
    sqlColumns: ["DATESTAMP", "LABNO", "TESTCODE", "TESTINDEX", "FRAMEREF"],
    fields: ["DATESTAMP", "LABNO", "TESTCODE", "TESTINDEX", "FRAMEREF", "PRE", "REF", "VALUE"],
    cursorColumn: "LABNO",
  },
  {
    alias: "audit",
    class: AUDTDATA,
    tableName: "[DisalabData].[dbo].[AUDTDATA]",
    sqlColumns: ["DATESTAMP", "LABNO", "AUDDateTime", "OCCURS", "WS"],
    fields: [
      "DATESTAMP",
      "LABNO",
      "AUDDateTime",
      "OCCURS",
      "WS",
      "_AuditCode",
      "_AuditUser",
      "_Auditdata",
    ],
    cursorColumn: "LABNO",
  },
  {
    alias: "history",
    class: HISDAT5,
    tableName: "[DisalabData].[dbo].[HISDAT5]",
    sqlColumns: ["DATESTAMP", "Location", "HospitalNo", "IDNo"],
    fields: [
      "DATESTAMP",
      "Location",
      "HospitalNo",
      "IDNo",
      "_PatientID",
      "_Name",
      "_FamilyLastName",
      "_MiddleName",
      "_GivenName",
      "Sex",
      "Address",
      "PhoneNumberBusiness",
      "PhoneNumberHome",
    ],
  },
  {
    alias: "storage",
    class: STOADAT5,
    tableName: "[DisalabData].[dbo].[STOADAT5]",
    sqlColumns: ["DATESTAMP", "CODE", "UPDATEDDATE", "SEQNO", "SPECTYPE", "LABNO", "REGION"],
    fields: [
      "DATESTAMP",
      "CODE",
      "UPDATEDDATE",
      "SEQNO",
      "SPECTYPE",
      "LABNO",
      "REGION",
      "_CODE",
    ],
  },
  {
    alias: "worklist",
    class: WLSTDAT6,
    tableName: "[DisalabData].[dbo].[WLSTDAT6]",
    sqlColumns: [
      "DATESTAMP",
      "AREA",
      "WLSTGROUP",
      "WLSTATUS",
      "REQUESTED_DATE",
      "PRIORITY",
      "LABNO",
      "REGION",
      "REQUESTED_Time",
      "TESTINDEX",
      "TESTCODE",
      "REVIEWER",
    ],
    fields: [
      "DATESTAMP",
      "AREA",
      "WLSTGROUP",
      "WLSTATUS",
      "REQUESTED_DATE",
      "PRIORITY",
      "LABNO",
      "REGION",
      "REQUESTED_Time",
      "TESTINDEX",
      "TESTCODE",
      "REVIEWER",
    ],
  },
  {
    alias: "print-queue",
    class: PRINTQ4,
    tableName: "[DisalabData].[dbo].[PRINTQ4]",
    sqlColumns: [
      "DATESTAMP",
      "QUEUE",
      "ROUTE",
      "LOCATION",
      "WARD",
      "DRCODE",
      "LABNO",
      "XPRINTSET",
      "LANGUAGE",
      "REPTYPE",
      "COPY_NO",
    ],
    fields: [
      "DATESTAMP",
      "QUEUE",
      "ROUTE",
      "LOCATION",
      "WARD",
      "DRCODE",
      "LABNO",
      "XPRINTSET",
      "LANGUAGE",
      "REPTYPE",
      "COPY_NO",
    ],
    notes: "Has a class-level Count method (faster than raw SELECT COUNT).",
  },
  {
    alias: "lock",
    class: LOCKDAT5,
    tableName: "[DisalabData].[dbo].[LOCKDAT5]",
    sqlColumns: ["DATESTAMP", "LOCKKEY", "WorkstationID"],
    fields: ["DATESTAMP", "LOCKKEY", "WorkstationID"],
  },
  {
    alias: "lab-number",
    class: LABNDAT4,
    tableName: "[DisalabData].[dbo].[LABNDAT4]",
    sqlColumns: ["DATESTAMP", "ID", "LABDATE", "LABNO"],
    fields: ["DATESTAMP", "ID", "LABDATE", "LABNO"],
  },
  {
    alias: "ridx-nid",
    class: RIDNIDX4,
    tableName: "[DisalabData].[dbo].[RIDNIDX4]",
    sqlColumns: ["IDNUMBER", "LABNO"],
    fields: ["IDNUMBER", "LABNO"],
  },
  {
    alias: "ridx-ref",
    class: RREFIDX4,
    tableName: "[DisalabData].[dbo].[RREFIDX4]",
    sqlColumns: ["REFNO", "LABNO"],
    fields: ["REFNO", "LABNO"],
  },
  {
    alias: "ridx-link",
    class: RLNKIDX4,
    tableName: "[DisalabData].[dbo].[RLNKIDX4]",
    sqlColumns: ["UNIQUEID", "REGDATE", "LABNO"],
    fields: ["UNIQUEID", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-location-id",
    class: RLIDIDX4,
    tableName: "[DisalabData].[dbo].[RLIDIDX4]",
    sqlColumns: ["LOCATION", "PID", "REGDATE", "LABNO"],
    fields: ["LOCATION", "PID", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-doctor",
    class: RDOCIDX4,
    tableName: "[DisalabData].[dbo].[RDOCIDX4]",
    sqlColumns: ["DOCTOR", "REGDATE", "LABNO"],
    fields: ["DOCTOR", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-taken",
    class: RTKNIDX5,
    tableName: "[DisalabData].[dbo].[RTKNIDX5]",
    sqlColumns: ["TAKENDATE", "INVOICENO"],
    fields: ["TAKENDATE", "INVOICENO"],
  },
  {
    alias: "ridx-name",
    class: RNAMIDX4,
    tableName: "[DisalabData].[dbo].[RNAMIDX4]",
    sqlColumns: ["SURNAME", "REGDATE", "LABNO"],
    fields: ["SURNAME", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-dob",
    class: RDOBIDX4,
    tableName: "[DisalabData].[dbo].[RDOBIDX4]",
    sqlColumns: ["DOBDATE", "LABNO"],
    fields: ["DOBDATE", "LABNO"],
  },
  {
    alias: "ridx-doctor-name",
    class: RDNMIDX4,
    tableName: "[DisalabData].[dbo].[RDNMIDX4]",
    sqlColumns: ["DOCTOR", "SURNAME", "REGDATE", "LABNO"],
    fields: ["DOCTOR", "SURNAME", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-soundex",
    class: RSNXIDX4,
    tableName: "[DisalabData].[dbo].[RSNXIDX4]",
    sqlColumns: ["SOUNDX", "REGDATE", "LABNO"],
    fields: ["SOUNDX", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-location-name",
    class: RLNMIDX4,
    tableName: "[DisalabData].[dbo].[RLNMIDX4]",
    sqlColumns: ["LOCATION", "SURNAME", "REGDATE", "LABNO"],
    fields: ["LOCATION", "SURNAME", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-location-soundex",
    class: RLSXIDX4,
    tableName: "[DisalabData].[dbo].[RLSXIDX4]",
    sqlColumns: ["LOCATION", "SOUNDX", "REGDATE", "LABNO"],
    fields: ["LOCATION", "SOUNDX", "REGDATE", "LABNO"],
  },
  {
    alias: "ridx-location",
    class: RLOCIDX4,
    tableName: "[DisalabData].[dbo].[RLOCIDX4]",
    sqlColumns: ["LOCATION", "WARD", "REGDATE", "LABNO"],
    fields: ["LOCATION", "WARD", "REGDATE", "LABNO"],
  },
  {
    alias: "param-dict",
    class: PARMDICT,
    tableName: "[DisaGlobal].[dbo].[PARMDICT]",
    sqlColumns: ["DATESTAMP", "CODE", "DESCRIPTION", "ABBREV", "ACTIVE"],
    fields: [
      "DATESTAMP",
      "ACTIVE",
      "CODE",
      "DESCRIPTION",
      "ABBREVIATION",
      "CONTEXT",
      "INDEX",
      "UNITS",
      "REFERENCE",
    ],
  },
  {
    alias: "comm-dict",
    class: COMMDICT,
    tableName: "[DisaGlobal].[dbo].[COMMDICT]",
    sqlColumns: ["CONTEXT", "CODE", "DESCRIPTION", "ACTIVE"],
    fields: ["Data", "CONTEXT", "CODE", "DESCRIPTION", "ACTIVE"],
  },
  {
    alias: "test-dict",
    class: TESTDICT,
    tableName: "[DisaGlobal].[dbo].[TESTDICT]",
    sqlColumns: ["DATESTAMP", "CODE", "DESCRIPTION", "ABBREV", "SECTION"],
    fields: [
      "DATESTAMP",
      "CODE",
      "DESCRIPTION",
      "ABBREV",
      "SECTION",
      "PARAMETERS",
      "_CODE",
      "_DESCRIPTION",
      "_ABBREVIATION",
      "_WORKAREA_GROUP",
    ],
  },
  {
    alias: "loc-dict",
    class: LOCNDIC4,
    tableName: "[DisaGlobal].[dbo].[LOCNDIC4]",
    sqlColumns: [
      "DATESTAMP",
      "CODE",
      "DESCRIPTION",
      "ABBREV",
      "TELEPHONE",
      "NAME",
      "POSTAL_ADDRESS1",
      "POSTAL_ADDRESS2",
      "POSTAL_ADDRESS3",
      "POSTAL_ADDRESS4",
      "POST_CODE",
      "ORGANISATION",
      "ACTIVE",
      "District",
      "FacilityType",
      "FacilityArrangement",
    ],
    fields: [
      "DATESTAMP",
      "CODE",
      "DESCRIPTION",
      "ABBREV",
      "TELEPHONE",
      "NAME",
      "POSTAL_ADDRESS1",
      "POSTAL_ADDRESS2",
      "POSTAL_ADDRESS3",
      "POSTAL_ADDRESS4",
      "POST_CODE",
      "ORGANISATION",
      "ACTIVE",
      "District",
      "FacilityType",
      "FacilityArrangement",
    ],
  },
  {
    alias: "sys-dict",
    class: SYSTDIC5,
    tableName: "[DisaGlobal].[dbo].[SYSTDIC5]",
    sqlColumns: ["DATESTAMP", "ID", "LABORATORY_NAME"],
    fields: ["DATESTAMP", "ID", "LABORATORY_NAME", "Prefixes"],
  },
  {
    // Composite-key dictionary: (CODE1, CODE2) → (DESCRIPTION, ABBREV).
    // CODE1 is typically a facility code (5 chars space-padded) and CODE2
    // the ward/clinical-service code under it. CODE1 = "@@@@@" is the
    // facility-agnostic sentinel. In Mozambique, DESCRIPTION/ABBREV are
    // NULL on disk — the values are packed into WARDDICT_STATUS bytes.
    alias: "ward-dict",
    class: WARDDICT,
    tableName: "[DisaGlobal].[dbo].[WARDDICT]",
    sqlColumns: ["DATESTAMP", "CODE1", "CODE2", "DESCRIPTION", "ABBREV"],
    fields: ["DATESTAMP", "CODE1", "CODE2", "DESCRIPTION", "ABBREV"],
    notes:
      "Composite key (CODE1, CODE2). Description/abbrev may be NULL on disk in some deployments; the values are encoded in WARDDICT_STATUS bytes.",
  },
  {
    alias: "order-dict",
    class: ORDRDIC5,
    tableName: "[DisalabDict].[dbo].[ORDRDIC5]",
    sqlColumns: ["DATESTAMP", "CODE", "LOCNCODE", "USAGE"],
    fields: [
      "DATESTAMP",
      "CODE",
      "LOCNCODE",
      "USAGE",
      "_CREATEDBY",
      "ADDITIONAL_INFO",
      "_CODE",
      "_USAGE",
      "_SECTION",
      "_AREA",
      "_GROUP",
      "_STORAGE",
      "_ROUTE",
      "_LABS_ALLOWED",
      "_RULES_ON_ORDER",
      "_RULES_ON_RESULT",
      "_RULES_ON_REVIEW",
      "_Orders",
    ],
  },
  {
    alias: "rule-dict",
    class: RULEDIC5,
    tableName: "[DisalabDict].[dbo].[RULEDIC5]",
    sqlColumns: ["DATESTAMP", "CODE"],
    fields: ["DATESTAMP", "CODE", "Rules"],
  },
  {
    alias: "work-dict",
    class: WRKADICT,
    tableName: "[DisalabDict].[dbo].[WRKADICT]",
    sqlColumns: ["DATESTAMP", "CODE", "DESCRIPTION", "ABBREV"],
    fields: [
      "DATESTAMP",
      "CODE",
      "DESCRIPTION",
      "ABBREV",
      "_CODE",
      "_DESCRIPTION",
      "_ABBREVIATION",
      "Location",
    ],
  },
  {
    alias: "breg-dict",
    class: BREGDICT,
    tableName: "[DisalabDict].[dbo].[BREGDICT]",
    sqlColumns: ["DATESTAMP", "CODE", "DESCRIPTION", "ABBREV"],
    fields: ["DATESTAMP", "CODE", "DESCRIPTION", "ABBREV", "_CODE", "_DESCRIPTION"],
  },
  {
    alias: "desl-dict",
    class: DESLDIC5,
    tableName: "[DisalabDict].[dbo].[DESLDIC5]",
    sqlColumns: [
      "DATESTAMP",
      "LANGUAGE",
      "CONTEXT",
      "CODE1",
      "CODE2",
      "CODE3",
      "DESCRIPTION",
      "ABBREV",
    ],
    fields: [
      "DATESTAMP",
      "LANGUAGE",
      "CONTEXT",
      "CODE1",
      "CODE2",
      "CODE3",
      "DESCRIPTION",
      "ABBREV",
      "_CONTEXT",
      "_CODE1",
      "_CODE2",
      "_CODE3",
      "_DESCRIPTION",
      "_ABBREVIATION",
      "_Sectors",
    ],
  },
  {
    alias: "docc-dat",
    class: DOCCDAT5,
    tableName: "[DisalabDict].[dbo].[DOCCDAT5]",
    sqlColumns: ["DATESTAMP", "CONTEXT", "CODE1", "CODE2", "CODE3", "CODE4"],
    fields: [
      "DATESTAMP",
      "CONTEXT",
      "CODE1",
      "CODE2",
      "CODE3",
      "CODE4",
      "_CONTEXT",
      "_CODE1",
      "_CODE2",
      "_CODE3",
      "_CODE4",
    ],
  },
];

const aliasMap = new Map<string, EntityDef>();
for (const def of ENTITY_DEFS) aliasMap.set(def.alias, def);

const classNameMap = new Map<string, EntityDef>();
for (const def of ENTITY_DEFS) {
  const className = (def.class as unknown as { name: string }).name;
  classNameMap.set(className, def);
  classNameMap.set(className.toUpperCase(), def);
}

export function listEntities(): EntityDef[] {
  return [...ENTITY_DEFS];
}

export function resolveEntity(aliasOrClassName: string): EntityDef {
  const byAlias = aliasMap.get(aliasOrClassName);
  if (byAlias !== undefined) return byAlias;
  const byClass = classNameMap.get(aliasOrClassName);
  if (byClass !== undefined) return byClass;
  const byUpper = classNameMap.get(aliasOrClassName.toUpperCase());
  if (byUpper !== undefined) return byUpper;
  const known = [...aliasMap.keys()].sort();
  throw new Error(
    `Unknown entity: ${aliasOrClassName}. Known aliases: ${known.join(", ")}. (Raw DB class names also accepted.)`,
  );
}
